//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BennetVellaSecureSoftware.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Publishes = new HashSet<Publish>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastEdited { get; set; }
        public int StateId { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string FileName { get; set; }
        public string Signature { get; set; }
        [Required]
        public string Title { get; set; }
    
        public virtual ArticleState ArticleState { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Review Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publish> Publishes { get; set; }
    }
}
